baseurl = "https://jordancrane.me"
theme = "hugo-coder"
languagecode = "en-us"
defaultContentLanguage = "en"
isMultilingual = false
title = "Jordan Crane"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Jordan Crane"
    info = "Backend Software Engineer"
    description = "Jordan Crane's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "Jordan Crane's personal website"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jordancrane/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/jordancrane/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 3
    url = "https://www.instagram.com/jcrvne"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "https://resume.jordancrane.me"
